name: son_depremler
description: A flutter app that shows latest earthquakes.

version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Localization
  easy_localization: ^3.0.8

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # State
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Network
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  # Navigation
  go_router: ^16.3.0

  # Audio
  audioplayers: ^6.5.1

  # Splash
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  # App Icon
  flutter_launcher_icons: ^0.14.4

  # Package Name
  change_app_package_name: ^1.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ic_appicon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F0F5F9"
  image: "assets/images/ic_appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Thin.ttf
